//@host = localhost:3000
@host = mongodb-contacts.onrender.com

@objectid_1 = 6444a1a14e023dbc80cd19cc
@objectid_2 = 6444a1a14e023dbc80cd19cd
@objectid_3 = 6444a1a14e023dbc80cd19ce
@objectid_4 = 6444a1a14e023dbc80cd19cf

### List all contacts
GET http://{{host}}/contacts

### Find contact by ID
GET http://{{host}}/contacts/{{objectid_1}}

###
GET http://{{host}}/contacts/{{objectid_2}}

###
GET http://{{host}}/contacts/{{objectid_3}}

### Not found
GET http://{{host}}/contacts/{{objectid_4}}

### Add new contact
POST http://{{host}}/contacts
Content-Type: application/json

{
  "firstName": "Santa",
  "lastName": "Claus",
  "email": "big.elf@north.pole.org",
  "favoriteColor": "candy cane red",
  "birthday": "12/25/0000"
}

### Update contact (partial record OK)
PUT http://{{host}}/contacts/{{objectid_1}}
Content-Type: application/json

{
  "firstName": "Santa",
  "lastName": "Claus"
}

### Restore contact
PUT http://{{host}}/contacts/{{objectid_1}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "favoriteColor": "beige",
  "birthday": "1980-01-01"
}

### Delete contact (ID is malformed)
DELETE http://{{host}}/contacts/bogusid

### Delete contact
# @prompt id_to_delete Enter a valid record ID
DELETE http://{{host}}/contacts/{{id_to_delete}}
